spring.application.name=transactions

#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.url=jdbc:postgresql://db:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=temppassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update

management.endpoints.web.exposure.include=health
management.endpoint.health.probes.enabled=true
# management.endpoint.health.show-details=always
